# Guessing FLOOR MODELS

In [2]:
# basic
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# estimators


from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
#from sklearn.linear_model import LinearRegression, Ridge, Lasso

# Classification Models
from sklearn.svm import LinearSVC
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

# tools
from sklearn.model_selection import train_test_split

# regression model metrics
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score

# classification model metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report


#Hyper parameter tuning
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

# To save the ML models
import joblib

In [11]:
def makePredictions (loaded_model, X_test, y_test):
    model_predictions = loaded_model.predict(X_test)

    print(accuracy_score(y_test, model_predictions))
    print(confusion_matrix(y_test, model_predictions))

In [5]:
path = '/home/ale/Dropbox/UBIQUM/4.DeepAnalytics&Visualization/T4M3.WiFiLocationing/Data/'
file_X = "2_DataPrepro_Floor_X.csv"
file_y = "2_DataPrepro_Floor_y.csv"

Saved_X = pd.read_csv(path + file_X)
Saved_y = pd.read_csv(path + file_y)

print(Saved_y.head())
Saved_X.head()


   FLOOR
0      2
1      3
2      2
3      0
4      3


WAP001  WAP002  WAP003  WAP004  WAP005  WAP006  WAP007  WAP008  WAP009  \
0     100     100     100     100     100     100     100     100     100   
1     100     100     100     100     100     100     100     100     100   
2     100     100     100     100     100     100     100     100     100   
3     100     100     100     100     100     100     100     100     100   
4     100     100     100     100     100     100     100     100     100   

   WAP010  ...  WAP509  WAP510  WAP511  WAP512  WAP515  WAP516  WAP517  \
0     100  ...     100     100     100     100     100     100     100   
1     100  ...     100     100     100     100     100     100     100   
2     100  ...     100     100     100     100     100     100     100   
3     100  ...     100     100     100     100     100     -83     -85   
4     100  ...     100     100     100     100     100     100     100   

   WAP518  WAP519  WAP520  
0     100     100     100  
1     100     100     100  
2     100     100     100  
3     100     100     100  
4     100     100     100  

[5 rows x 434 columns]

## 1.6 Train/Test Split

In [6]:
# define X and y
X = Saved_X
y = Saved_y

# define train/test_ratio
train_ratio = 0.75
test_ratio = 0.25

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=(1-train_ratio) )

# check dimensionsc
#print('DF: ', Tdata_Building.shape)
print('X:', X.shape,'y:', y.shape)
print('X_train:', X_train.shape,'y_train:', y_train.shape)
print('X_test: ', X_test.shape,' y_test: ', y_test.shape)

X: (8972, 434) y: (8972, 1)
X_train: (6729, 434) y_train: (6729, 1)
X_test:  (2243, 434)  y_test:  (2243, 1)


### Load k-NN

In [12]:
path = '/home/ale/Dropbox/UBIQUM/4.DeepAnalytics&Visualization/T4M3.WiFiLocationing/'
file = 'Floor_KNN.joblib'

# Load the model from the file
KNN_from_joblib = joblib.load(path + file)

# Use the loaded model to make predictions
makePredictions(KNN_from_joblib, X_test, y_test)

0.9768167632634864
[[506   3   0   9   0]
 [  9 532   5   3   0]
 [  1   3 487   8   0]
 [  0   0   8 550   1]
 [  0   0   0   2 116]]


### Load RF

In [13]:
path = '/home/ale/Dropbox/UBIQUM/4.DeepAnalytics&Visualization/T4M3.WiFiLocationing/'
file = 'Floor_RF.joblib'

# Load the model from the file
RF_from_joblib = joblib.load(path + file)

# Use the loaded model to make predictions
makePredictions(RF_from_joblib, X_test, y_test)

0.9772625947391886
[[507  10   1   0   0]
 [  3 542   3   1   0]
 [  1   8 483   7   0]
 [ 12   0   3 544   0]
 [  0   0   0   2 116]]


### Load LR

In [14]:
path = '/home/ale/Dropbox/UBIQUM/4.DeepAnalytics&Visualization/T4M3.WiFiLocationing/'
file = 'Floor_LR.joblib'

#Load the model from the file
LR_from_joblib = joblib.load(path + file)

# Use the loaded model to make predictions
makePredictions(LR_from_joblib, X_test, y_test)

0.9121711992866697
[[493  24   0   1   0]
 [ 25 504  15   5   0]
 [  2  26 427  44   0]
 [ 13   3  32 507   4]
 [  0   0   0   3 115]]
